/* ----------------- Account ---------------- */
export const loginTypes = {
  LOGGING: 'LOGGING',
  LOGOUT: 'LOGOUT',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CONFIRM_PASSWORD: 'CONFIRM_PASSWORD'
};

/* --------------- Customer -------------- */
export const customerTypes = {
  GET_DOCUMENTS_TYPE: "GET_DOCUMENTS_TYPE",
  REGISTER: "REGISTER",
  GET_COMPANIES: "GET_COMPANIES",
  NEW_REGISTER: "NEW_REGISTER",
  GET_HOME_DATA: "GET_HOME_DATA",
  GET_REQUEST_DATA: "GET_REQUEST_DATA",
  GET_OUTLAY_DATA: "GET_OUTLAY_DATA",
  GET_OUTLAY_DATESLIST: "GET_OUTLAY_DATESLIST",
  GET_ACCOUNT_DETAIL:  "GET_ACCOUNT_DETAIL",
  GENERATE_DOCUMENTS: "GENERATE_DOCUMENTS",
  CREATE_REQUEST: "CREATE_REQUEST",
  UPDATE_REQUEST_DOCUMENTS: "UPDATE_REQUEST_DOCUMENTS",
  UPDATE_REQUEST_INFORMATION: "UPDATE_REQUEST_INFORMATION",
  GET_TRANSACTIONS_LIST: "GET_TRANSACTIONS_LIST",
  GET_REQUEST_LIST: "GET_REQUEST_LIST",
  GET_OUTLAYED_REQUEST_LIST: "GET_OUTLAYED_REQUEST_LIST",
  GET_REJECTED_REQUEST_LIST: "GET_REJECTED_REQUEST_LIST",
  GENERATE_CODES: "GENERATE_CODES",
  CHECK_CODES: "CHECK_CODES",
  RESET_VALUES: "RESET_VALUES",
};

/* ----------------- Company ------------------- */
export const companyTypes = {
  GET_REQUEST_LIST: "GET_REQUEST_LIST",
};

/* ----------------- Admin ------------------- */
export const adminTypes = {
  GET_ALL_CUSTOMERS: "GET_ALL_CUSTOMERS",
  GET_CUSTOMERS_TO_APPROVE: "GET_CUSTOMERS_TO_APPROVE",
  GET_CUSTOMERS_COUNT_TO_APPROVE: "GET_CUSTOMERS_COUNT_TO_APPROVE",
  GET_DATELIST_TO_CUSTOMER: "GET_DATELIST_TO_CUSTOMER",
  APPROVE_CUSTOMERS: "APPROVE_CUSTOMERS",
  PASS_WITH_DOCUMENTS_REQUEST: "PASS_WITH_DOCUMENTS_REQUEST",
  PASS_WITHOUT_CHANGES_REQUEST: "PASS_WITHOUT_CHANGES_REQUEST",
  PASS_TO_OUTLAY: "PASS_TO_OUTLAY",
  GET_ALL_COMPANIES: "GET_ALL_COMPANIES",
  GET_COMPANY_WITH_SALARY: "GET_COMPANY_WITH_SALARY",
  REGISTER_ADMIN: "REGISTER_ADMIN",
  CREATE_COMPANY: "CREATE_COMPANY",
  UPDATE_COMPANY: "UPDATE_COMPANY",
  UPDATE_COMPANY_SALARIES: "UPDATE_COMPANY_SALARIES",
  DELETE_CUSTOMERS: "DELETE_CUSTOMERS",
  CREATE_CUSTOMER: "CREATE_CUSTOMER",
  ACTIVATE_CUSTOMER: "ACTIVATE_CUSTOMER",
  ACTIVATE_COMPANY: "ACTIVATE_COMPANY",
  UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
  CREATE_MULTIPLE_CUSTOMER: "CREATE_MULTIPLE_CUSTOMER",
  GET_REQUEST_LIST: "GET_REQUEST_LIST",
  GET_REJECTED_REQUEST: "GET_REJECTED_REQUEST",
  GET_DEFINITELY_REJECTED_REQUEST: "GET_DEFINITELY_REJECTED_REQUEST",
  GET_PENDINGRH_REQUEST: "GET_PENDINGRH_REQUEST",
  GET_REQUEST_TO_APPROVE: "GET_REQUEST_TO_APPROVE",
  GET_REQUEST_TO_OUTLAY: "GET_REQUEST_TO_OUTLAY",
  GET_REQUEST_BANK_REFUNDED: "GET_REQUEST_BANK_REFUNDED",
  GET_REQUEST_PROCESS_WITHOUT_CHANGE: "GET_REQUEST_PROCESS_WITHOUT_CHANGE",
  GET_REQUEST_PROCESS_DOCUMENTS_CHANGE: "GET_REQUEST_PROCESS_DOCUMENTS_CHANGE",
  GET_REQUEST_PROCESS_INBANK: "GET_REQUEST_PROCESS_INBANK",
  GET_FINALIZED_REQUEST: "GET_FINALIZED_REQUEST",
  GENERATE_BANK_REPORT: "GENERATE_BANK_REPORT",
  RECEIVE_BANK_FILE: "RECEIVE_BANK_FILE",
  RESET_VALUES: "RESET_VALUES"
};

/* ---------------- General --------------------- */
export const generalTypes = {
  APPROVE_REJECT_REQUEST: "APPROVE_REJECT_REQUEST",
  GET_CUSTOMER_LIST: "GET_CUSTOMER_LIST",
  GET_CUSTOMER_REPORT: "GET_CUSTOMER_REPORT",
  GET_COMPANY_REPORT: "GET_COMPANY_REPORT",
};

export const integrationTypes = {
  INTEGRATION_REGISTER: "INTEGRATION_REGISTER",
};

