/* ----------------- Account ---------------- */
export const loginTypes = {
  LOGGING: 'LOGGING',
  LOGOUT: 'LOGOUT',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CONFIRM_PASSWORD: 'CONFIRM_PASSWORD'
};

/* --------------- Customer -------------- */
export const customerTypes = {
  GET_DOCUMENTS_TYPE: "GET_DOCUMENTS_TYPE",
  REGISTER: "REGISTER",
  GET_HOME_DATA: "GET_HOME_DATA",
  GET_REQUEST_DATA: "GET_REQUEST_DATA",
  GET_OUTLAY_DATA: "GET_OUTLAY_DATA",
  GET_OUTLAY_DATESLIST: "GET_OUTLAY_DATESLIST",
  GENERATE_DOCUMENTS: "GENERATE_DOCUMENTS",
  CREATE_REQUEST: "CREATE_REQUEST",
  GET_TRANSACTIONS_LIST: "GET_TRANSACTIONS_LIST",
  GET_REQUEST_LIST: "GET_REQUEST_LIST",
};


